spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jiang-alibaba?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:
    timeout: 300ms
  zipkin:
    base-url: http://localhost:9411
    locator:
      discovery:
        enabled: true
    discovery-client-enabled: false
  sleuth:
    sampler:
      probability: 1.0
  boot:
    admin:
      client:
        url: http://localhost:8095

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

# 过滤不需要认证路径条件
secure:
  ignored:
    urls: #安全路径白名单
      - /actuator/**
      - /druid/**
      - /admin/login
      - /file/upload


jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: jiang-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: Bearer  #JWT负载中拿到开头

redis:
  database: jiang
  key:
    admin: 'ums:admin'
    resourceList: 'ums:resourceList'
  expire:
    common: 86400 # 24小时
logging:
  level:
    root: info #日志配置DEBUG,INFO,WARN,ERROR
    com.alibaba.jiangumsserver: debug

mybatis-plus:
  mapper-locations: classpath*:/dao/**/*.xml
  type-aliases-package: com.alibaba.jiangumsserver.model.*
  global-config:
    db-config:
      id-type: AUTO
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'NULL'