spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:
    timeout: 300ms
  boot:
    admin:
      client:
        url: http://localhost:8095 #admin服务器地址
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
# 过滤不需要认证路径条件,后续的路径直接往下加就行
secure:
  ignored:
    urls:
      - /actuator/**
      - /druid/**
      - /admin/login
